-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Galerie.Object.Artist_max_fields exposing (..)

import Galerie.InputObject
import Galerie.Interface
import Galerie.Object
import Galerie.Scalar
import Galerie.ScalarCodecs
import Galerie.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


created_at : SelectionSet (Maybe Galerie.ScalarCodecs.Timestamptz) Galerie.Object.Artist_max_fields
created_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "created_at" [] (Galerie.ScalarCodecs.codecs |> Galerie.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


updated_at : SelectionSet (Maybe Galerie.ScalarCodecs.Timestamptz) Galerie.Object.Artist_max_fields
updated_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "updated_at" [] (Galerie.ScalarCodecs.codecs |> Galerie.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)
