-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Galerie.Object.Artwork exposing (..)

import Galerie.InputObject
import Galerie.Interface
import Galerie.Object
import Galerie.Scalar
import Galerie.ScalarCodecs
import Galerie.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| An object relationship
-}
artist : SelectionSet decodesTo Galerie.Object.Artist -> SelectionSet decodesTo Galerie.Object.Artwork
artist object_ =
    Object.selectionForCompositeField "artist" [] object_ identity


artist_id : SelectionSet Galerie.ScalarCodecs.Uuid Galerie.Object.Artwork
artist_id =
    Object.selectionForField "ScalarCodecs.Uuid" "artist_id" [] (Galerie.ScalarCodecs.codecs |> Galerie.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


created_at : SelectionSet Galerie.ScalarCodecs.Timestamptz Galerie.Object.Artwork
created_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "created_at" [] (Galerie.ScalarCodecs.codecs |> Galerie.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


description : SelectionSet String Galerie.Object.Artwork
description =
    Object.selectionForField "String" "description" [] Decode.string


height : SelectionSet Int Galerie.Object.Artwork
height =
    Object.selectionForField "Int" "height" [] Decode.int


id : SelectionSet Galerie.ScalarCodecs.Uuid Galerie.Object.Artwork
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (Galerie.ScalarCodecs.codecs |> Galerie.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


image_url : SelectionSet String Galerie.Object.Artwork
image_url =
    Object.selectionForField "String" "image_url" [] Decode.string


support : SelectionSet Galerie.ScalarCodecs.Name Galerie.Object.Artwork
support =
    Object.selectionForField "ScalarCodecs.Name" "support" [] (Galerie.ScalarCodecs.codecs |> Galerie.Scalar.unwrapCodecs |> .codecName |> .decoder)


techniques : SelectionSet String Galerie.Object.Artwork
techniques =
    Object.selectionForField "String" "techniques" [] Decode.string


title : SelectionSet Galerie.ScalarCodecs.Name Galerie.Object.Artwork
title =
    Object.selectionForField "ScalarCodecs.Name" "title" [] (Galerie.ScalarCodecs.codecs |> Galerie.Scalar.unwrapCodecs |> .codecName |> .decoder)


updated_at : SelectionSet Galerie.ScalarCodecs.Timestamptz Galerie.Object.Artwork
updated_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "updated_at" [] (Galerie.ScalarCodecs.codecs |> Galerie.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


width : SelectionSet Galerie.ScalarCodecs.Interval Galerie.Object.Artwork
width =
    Object.selectionForField "ScalarCodecs.Interval" "width" [] (Galerie.ScalarCodecs.codecs |> Galerie.Scalar.unwrapCodecs |> .codecInterval |> .decoder)
