-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Galerie.Object.Artwork_max_fields exposing (..)

import Galerie.InputObject
import Galerie.Interface
import Galerie.Object
import Galerie.Scalar
import Galerie.ScalarCodecs
import Galerie.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


created_at : SelectionSet (Maybe Galerie.ScalarCodecs.Timestamptz) Galerie.Object.Artwork_max_fields
created_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "created_at" [] (Galerie.ScalarCodecs.codecs |> Galerie.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


description : SelectionSet (Maybe String) Galerie.Object.Artwork_max_fields
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


height : SelectionSet (Maybe Int) Galerie.Object.Artwork_max_fields
height =
    Object.selectionForField "(Maybe Int)" "height" [] (Decode.int |> Decode.nullable)


image_url : SelectionSet (Maybe String) Galerie.Object.Artwork_max_fields
image_url =
    Object.selectionForField "(Maybe String)" "image_url" [] (Decode.string |> Decode.nullable)


techniques : SelectionSet (Maybe String) Galerie.Object.Artwork_max_fields
techniques =
    Object.selectionForField "(Maybe String)" "techniques" [] (Decode.string |> Decode.nullable)


updated_at : SelectionSet (Maybe Galerie.ScalarCodecs.Timestamptz) Galerie.Object.Artwork_max_fields
updated_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "updated_at" [] (Galerie.ScalarCodecs.codecs |> Galerie.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)
