-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Galerie.Object.Artwork exposing (..)

import Galerie.InputObject
import Galerie.Interface
import Galerie.Object
import Galerie.Scalar
import Galerie.ScalarCodecs
import Galerie.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


artist : SelectionSet decodesTo Galerie.Object.Artist -> SelectionSet (Maybe decodesTo) Galerie.Object.Artwork
artist object_ =
    Object.selectionForCompositeField "artist" [] object_ (identity >> Decode.nullable)


artist_id : SelectionSet (Maybe String) Galerie.Object.Artwork
artist_id =
    Object.selectionForField "(Maybe String)" "artist_id" [] (Decode.string |> Decode.nullable)


created_at : SelectionSet (Maybe String) Galerie.Object.Artwork
created_at =
    Object.selectionForField "(Maybe String)" "created_at" [] (Decode.string |> Decode.nullable)


description : SelectionSet (Maybe String) Galerie.Object.Artwork
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


exhibition_ids : SelectionSet (Maybe (List (Maybe String))) Galerie.Object.Artwork
exhibition_ids =
    Object.selectionForField "(Maybe (List (Maybe String)))" "exhibition_ids" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


exhibitions : SelectionSet decodesTo Galerie.Object.Exhibition -> SelectionSet (Maybe (List (Maybe decodesTo))) Galerie.Object.Artwork
exhibitions object_ =
    Object.selectionForCompositeField "exhibitions" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


height : SelectionSet (Maybe Float) Galerie.Object.Artwork
height =
    Object.selectionForField "(Maybe Float)" "height" [] (Decode.float |> Decode.nullable)


id : SelectionSet String Galerie.Object.Artwork
id =
    Object.selectionForField "String" "id" [] Decode.string


image_url : SelectionSet String Galerie.Object.Artwork
image_url =
    Object.selectionForField "String" "image_url" [] Decode.string


support : SelectionSet (Maybe String) Galerie.Object.Artwork
support =
    Object.selectionForField "(Maybe String)" "support" [] (Decode.string |> Decode.nullable)


techniques : SelectionSet (Maybe String) Galerie.Object.Artwork
techniques =
    Object.selectionForField "(Maybe String)" "techniques" [] (Decode.string |> Decode.nullable)


title : SelectionSet (Maybe String) Galerie.Object.Artwork
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


updated_at : SelectionSet (Maybe String) Galerie.Object.Artwork
updated_at =
    Object.selectionForField "(Maybe String)" "updated_at" [] (Decode.string |> Decode.nullable)


width : SelectionSet (Maybe Float) Galerie.Object.Artwork
width =
    Object.selectionForField "(Maybe Float)" "width" [] (Decode.float |> Decode.nullable)
