-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Galerie.Object.ExposedArtwork exposing (..)

import Galerie.InputObject
import Galerie.Interface
import Galerie.Object
import Galerie.Scalar
import Galerie.ScalarCodecs
import Galerie.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


artwork : SelectionSet decodesTo Galerie.Object.Artwork -> SelectionSet (Maybe decodesTo) Galerie.Object.ExposedArtwork
artwork object_ =
    Object.selectionForCompositeField "artwork" [] object_ (identity >> Decode.nullable)


artwork_id : SelectionSet (Maybe String) Galerie.Object.ExposedArtwork
artwork_id =
    Object.selectionForField "(Maybe String)" "artwork_id" [] (Decode.string |> Decode.nullable)


created_at : SelectionSet (Maybe String) Galerie.Object.ExposedArtwork
created_at =
    Object.selectionForField "(Maybe String)" "created_at" [] (Decode.string |> Decode.nullable)


exhibition : SelectionSet decodesTo Galerie.Object.Exhibition -> SelectionSet (Maybe decodesTo) Galerie.Object.ExposedArtwork
exhibition object_ =
    Object.selectionForCompositeField "exhibition" [] object_ (identity >> Decode.nullable)


exhibition_id : SelectionSet (Maybe String) Galerie.Object.ExposedArtwork
exhibition_id =
    Object.selectionForField "(Maybe String)" "exhibition_id" [] (Decode.string |> Decode.nullable)


id : SelectionSet String Galerie.Object.ExposedArtwork
id =
    Object.selectionForField "String" "id" [] Decode.string


updated_at : SelectionSet (Maybe String) Galerie.Object.ExposedArtwork
updated_at =
    Object.selectionForField "(Maybe String)" "updated_at" [] (Decode.string |> Decode.nullable)
