-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Galerie.Enum.Artist_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "artist"

  - Artist\_pkey - unique or primary key constraint

-}
type Artist_constraint
    = Artist_pkey


list : List Artist_constraint
list =
    [ Artist_pkey ]


decoder : Decoder Artist_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "artist_pkey" ->
                        Decode.succeed Artist_pkey

                    _ ->
                        Decode.fail ("Invalid Artist_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Artist_constraint -> String
toString enum =
    case enum of
        Artist_pkey ->
            "artist_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Artist_constraint
fromString enumString =
    case enumString of
        "artist_pkey" ->
            Just Artist_pkey

        _ ->
            Nothing
