-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Galerie.Enum.Artwork_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "artwork"

  - Artwork\_pkey - unique or primary key constraint

-}
type Artwork_constraint
    = Artwork_pkey


list : List Artwork_constraint
list =
    [ Artwork_pkey ]


decoder : Decoder Artwork_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "artwork_pkey" ->
                        Decode.succeed Artwork_pkey

                    _ ->
                        Decode.fail ("Invalid Artwork_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Artwork_constraint -> String
toString enum =
    case enum of
        Artwork_pkey ->
            "artwork_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Artwork_constraint
fromString enumString =
    case enumString of
        "artwork_pkey" ->
            Just Artwork_pkey

        _ ->
            Nothing
