-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Galerie.Object exposing (..)


type Artist
    = Artist


type Artwork
    = Artwork


type Exhibition
    = Exhibition


type ExposedArtwork
    = ExposedArtwork


type SubscribedQuery
    = SubscribedQuery


type User
    = User


type WebsocketConnection
    = WebsocketConnection
